[CRES-110] 멤버 모달 개선
crescenders/crescendo-frontend pull request #159
Opened 2023-10-31 11:45 UTC by overtae

## 🚅 PR 한 줄 요약

- close #158

## 🧑‍💻 PR 세부 내용

- 멤버 목록 조회 시 리더 먼저 보여지도록 정렬
- 신청 거절 및 멤버 추방 시 낙관적 업데이트 적용
- 신청 거절 및 멤버 추방 시 경고 모달 추가

## 📸 스크린샷 or GIF

2023-11-02 07:05 UTC, thyeone requested changes
👍

2023-11-02 07:05 UTC, thyeone commented on src/hooks/mutations/useReplyApplication.ts
> +      );
useGetApplications의 타입은 Application[] 아닌가용?!

그리구 타입 단언보다 getQuerydata<Application[]> 처럼 작성하는 것도 좋을 고 같아여

2023-11-02 07:20 UTC, thyeone commented on src/components/member/MemberList.tsx
> +            isCurrentUserLeader={checkIsLeader()}
함수를 호출시킨 상태로 전달하기 위한 의도일까요?!

2023-11-02 14:08 UTC, overtae commented on src/components/member/MemberList.tsx
>    if (isError && error.response?.status === 403) {
오오 알겠습니다!!

2023-11-02 14:26 UTC, overtae commented on src/components/member/MemberList.tsx
> +            isCurrentUserLeader={checkIsLeader()}
헛 네 맞습니다..

2023-11-02 17:19 UTC, thyeone approved these changes
고생하셨습니다!

2023-11-03 06:22 UTC, thyeone approved these changes

2023-11-03 13:56 UTC, merged