[CRES-122] 사이트 제목 및 파비콘 등록
crescenders/crescendo-frontend pull request #175
Opened 2023-11-09 13:53 UTC by overtae

## 🚅 PR 한 줄 요약

- close #174 

## 🧑‍💻 PR 세부 내용

- 사이트 제목 등록
- Next.js 기본 파비콘 > 프로젝트 로고 파비콘으로 변경

## 📸 스크린샷 or GIF

![image](https://github.com/crescenders/crescendo-frontend/assets/51291185/945f4ad1-d8da-4a1a-97e3-68888a52abfa)

2023-11-09 14:57 UTC, thyeone approved these changes
~👍

2023-11-10 19:24 UTC, thyeone commented on src/components/common/CustomHead.tsx
고생많으셨습니다,,

모든 페이지마다 공통적으로 적용되어서 _document에 작성하시는 건 어떨까요?

2023-11-12 07:06 UTC, thyeone requested changes

2023-11-12 07:06 UTC, thyeone commented on src/pages/sitemap.xml.tsx
<img width="747" alt="image" src="https://github.com/crescenders/crescendo-frontend/assets/48711263/6af4b5d5-7e1c-49b2-bd88-20833bef0920">
와우... 멋집니다👍

2023-11-12 07:06 UTC, thyeone commented on src/pages/sitemap.xml.tsx
> +    let response = await studyApi.getStudyGroupList(`?${cursor}`);
별도의 빌드없이 getInitialProps로 동적으로 sitemap을 생성하는 게 너무 좋은데요..

getInitialProps가 레거시여서 getServerSideProps로만 수정하면 좋을 것 같아요!

2023-11-12 12:53 UTC, overtae commented on src/pages/_document.tsx
> +      <CustomHead />
헐 따로 에러가 안나서 적용되는 줄 알았는데 아니었군요.... 수정하겠슴니다..

2023-11-12 12:53 UTC, overtae commented on src/pages/sitemap.xml.tsx
> +    let response = await studyApi.getStudyGroupList(`?${cursor}`);
허걱스 레거시였군요 알겠습니다!!

2023-11-12 13:25 UTC, thyeone approved these changes

2023-11-12 17:02 UTC, thyeone approved these changes
리뷰 반영하느라 고생 많으셨습니다.👍

2023-11-13 05:55 UTC, merged