[CRES-44] 토스트 메시지 컴포넌트 구현
crescenders/crescendo-frontend pull request #50
Opened 2023-08-07 11:21 UTC by overtae

## 🚅 PR 한 줄 요약

- close #47 

## 🧑‍💻 PR 세부 내용

- `useToast` 커스텀 훅 작성
- Toast 컴포넌트 작성
- 0.5초 후 자연스럽게 사라지는 애니메이션 추가
- 사용 예시
   ```jsx
    const { showToast } = useToast();

    const handleOnClick = () => {
      // toast type: 'success' 또는 'fail' 문자열만 사용가능합니다.
      showToast({ type: 'success', message: '성공했습니다.' });
    };
    ```

## 💡참고 사항

GIF에 미처 포함하진 못했지만, 사용자가 5초 안에(토스트 메시지가 사라지기 전에) 다른 페이지로 이동할 경우 토스트 메시지가 남아있도록 작업했습니다. 혹시 의도하신 기획이 해당 페이지에서만 보이게 하는 것이었다면 수정하도록 하겠습니다.

## 📸 스크린샷 or GIF

![toast-msg](https://github.com/crescenders/crescendo-frontend/assets/51291185/ff716fb5-36dd-48e7-b5f7-401b69f13547)

2023-08-07 15:17 UTC, thyeone requested changes

2023-08-07 16:20 UTC, thyeone requested changes
미처 생각 못했는데 한 수 더 생각해서 사라지기 전에 남아있게 구현하신 거 좋은 거 같아요👍
고생하셨습니다! 코멘트 확인 부탁드릴게요

2023-08-07 16:20 UTC, thyeone commented on src/components/common/Toast.tsx
> +const ToastItem = ({ type, message }) => {
한 파일 안에서 관리해도 굳이 문제될 건 안 보이지만 분리하지 않으신 이유가 있나요?

전역 변수로 선언하면 가비지 컬렉션이 안 된다는 말을 얼핏 들은 적이 있어서 찾아보니까 수집은 잘 된다고 하네요!
[링크](https://velog.io/@apparatus1/React%EC%97%90%EC%84%9C-%EC%A0%84%EC%97%AD%EC%97%90-%EB%B3%80%EC%88%98%EB%A5%BC-%EC%84%A0%EC%96%B8%ED%95%98%EB%A9%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-Garbage-Collection-%EB%90%A0%EA%B9%8C)

2023-08-07 16:20 UTC, thyeone commented on src/components/common/Toast.tsx
> +};
토스트 메세지도 모달처럼 동일하게 포탈을 하나 생성해서 랩핑하는 건 어떨까요?

2023-08-07 16:20 UTC, thyeone commented on src/hooks/useToast.ts
> +  );
요즘 추세가 비용이 많이 드는 계산이 아니거나 시각적으로 렌더링이 심하게 발생하지 않는 이상 메모이제이션을 하지 않는 것으로 정립된 거 같아요.
저도 최근에 비슷한 로직에 useCallback을 사용했다가 제거했는데, 이 경우도 useCallback을 사용하지 않는 것은 어떨까요?

https://snack.wiki/react-usememo/

2023-08-07 16:20 UTC, thyeone commented on src/components/common/Layout.tsx
> +      <Toast />
단순한 궁금증인데 페이지 이동 시 토스트 메세지가 사라지게 구현하시려는게 최상위 컴포넌트가 아닌 페이지 내에서 개별적으로 관리하도록 하는 것이였나요?!

2023-08-10 00:51 UTC, overtae commented on src/components/common/Toast.tsx
> +const ToastItem = ({ type, message }) => {
작업 당시 제가 했던 생각은, ToastItem이 Toast에서만 쓰이는데 파일을 나눠서 `components/toast` 폴더 내부에 넣어도 될까? 였습니다.. 다른 manage나 modal 같은 폴더를 살펴봤을 때 파일 하나하나마다 각각의 쓰임이 있는 것 같아서 결국 common 폴더에 한 파일로 작성하는 방법을 사용하게 되었습니다. 가비지 컬렉션은.. 생각하지 못했는데 다행입니다 ㅠㅠㅠ

2023-08-10 00:52 UTC, overtae commented on src/components/common/Toast.tsx
> +};
오 괜찮은 것 같습니다!

2023-08-10 00:53 UTC, overtae commented on src/hooks/useToast.ts
> +  );
아이고 글 읽어보니까 정말 그러네요... 자료 감사합니다. useCallback은 수정하도록 할게요!

2023-08-10 01:01 UTC, overtae commented on src/components/common/Layout.tsx
> +      <Toast />
최대한 최상위 컴포넌트에서 관리하는 방향으로 작업하고 싶었지만 여러가지 방법을 생각해봤는데 페이지 내에서 추가적으로 관리가 들어가게 될 것 같습니다..

2023-08-10 03:54 UTC, thyeone commented on src/components/common/Toast.tsx
> +const ToastItem = ({ type, message }) => {
아 폴더 생성까진 과한 거 같고 이렇게 가져가는 걸로 해요!

2023-08-10 03:55 UTC, thyeone commented on src/components/common/Layout.tsx
> +      <Toast />
저도 지금처럼 가져가는 게 가장 이상적이라고 생각해요! 좋습니당~~

2023-08-10 04:13 UTC, thyeone approved these changes
감사합니다.. 고생하셨어요!! :)

2023-08-10 04:30 UTC, overtae commented on src/components/common/Toast.tsx
> +import ToastLayout from '@components/portal/ToastPortal';
현재 모달 컴포넌트에서 ModalPortal을 ModalLayout으로 사용하고 있어서 동일하게 했는데, ToastPortal이 나으려나요?!

2023-08-10 06:32 UTC, overtae commented
`Layout` -> `Portal`로 변경 했습니다! 머지 할게요!

2023-08-10 06:33 UTC, merged